---
title: "Seminário Estatística Não-Paramétrica"
author: "Pedro de Oliveira Macedo"
date: '2023-08-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Carregar dados

```{r}
dados <- read.csv("housing.csv")
dados <- dados %>% mutate(ocean_proximity2 = ifelse(ocean_proximity == "INLAND",1,0))
```

## Subdividir em Treino x Teste

```{r}
set.seed(335944)
rv <- sample(2,nrow(dados), replace=T, prob = c(0.75,0.25))
dados_treino <- dados[rv==1,]
dados_teste <- dados[rv==2, ]
```


# Carregar pacotes

```{r, message=F}
library(dplyr)
library(ggplot2)
library(rpart)
library(rpart.plot)
```

# Descrição do banco

*escrever descrição das variáveis*

```{r}
head(dados)
```


# Motivação

```{r}
ggplot(data=dados, aes(x=median_income, y=median_house_value)) +
  geom_point()


```

# Decision Tree 1

```{r}
tree1 <- rpart(ocean_proximity2 ~ median_house_value, data=dados_treino)
rpart.plot(tree1)
```

## Predição

```{r}
preds1 <- predict(tree, dados_teste)

table1 <- table(preds1, dados_teste$ocean_proximity2)
table1

table1.1 <- data.frame()
for (i in 1:nrow(table1)) {
   table1.1[i,1] <- (table1[i,1])/(table1[i,1]+table1[i,2])
   table1.1[i,2] <- (table1[i,2])/(table1[i,1]+table1[i,2])
}
rownames(table1.1) = sort(unique(preds1))
colnames(table1.1) = c(0,1)

table1.1
```



# Decision Tree 2

```{r}
tree2 <- rpart(ocean_proximity2 ~ median_house_value + housing_median_age + total_rooms + total_bedrooms + population + households + median_income, data=dados_treino)
rpart.plot(tree2)
```

## Predição

```{r}
preds2 <- predict(tree2, dados_teste)

table2 <- table(preds2, dados_teste$ocean_proximity2)
table2

table2.1 <- data.frame()
for (i in 1:nrow(table2)) {
   table2.1[i,1] <- (table2[i,1])/(table2[i,1]+table2[i,2])
   table2.1[i,2] <- (table2[i,2])/(table2[i,1]+table2[i,2])
}
rownames(table2.1) = sort(unique(preds2))
colnames(table2.1) = c(0,1)

table2.1
```